import { useState } from 'react'
import api from '../../lib/api'
import toast from 'react-hot-toast'
import { Sparkles, RefreshCw, Copy, Printer } from 'lucide-react'

export default function AIBudgetAdvisor({ spiritualYear }) {
  const [loading, setLoading] = useState(false)
  const [advice, setAdvice] = useState(null)
  const [generatedAt, setGeneratedAt] = useState(null)
  const [error, setError] = useState(null)

  const generate = async () => {
    if (!spiritualYear) return toast.error('Select a financial year first')
    setLoading(true)
    setError(null)
    try {
      const res = await api.post('/ai/treasury/budget-advice', { spiritual_year: spiritualYear })
      setAdvice(res.data.advice)
      setGeneratedAt(new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }))
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate advice')
      toast.error('AI advisor failed')
    } finally { setLoading(false) }
  }

  const copy = () => {
    if (!advice) return
    navigator.clipboard.writeText(advice)
    toast.success('Copied to clipboard!')
  }

  const print = () => {
    if (!advice) return
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>MUTCU Budget Advisory — ${spiritualYear}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#04003D;max-width:700px;margin:0 auto;}
      h1{color:#04003D;border-bottom:3px solid #FF9700;padding-bottom:10px;}
      p{line-height:1.8;color:#374151;}
      .footer{margin-top:40px;font-size:12px;color:#9CA3AF;border-top:1px solid #E5E7EB;padding-top:10px;}
      </style></head><body>
      <h1>MUTCU Budget Advisory Report</h1>
      <p><strong>Financial Year:</strong> ${spiritualYear}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p>
      <hr style="border:none;border-top:1px solid #E5E7EB;margin:20px 0;">
      ${advice.split('\n').map(p => p.trim() ? `<p>${p}</p>` : '').join('')}
      <div class="footer">Generated by MUTCU AI Assistant · portal.mutcu.org</div>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  return (
    <div className="card border border-purple-100">
      <div className="flex items-center justify-between p-4 border-b border-gray-50">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-purple-100 rounded-lg flex items-center justify-center">
            <Sparkles size={14} className="text-purple-600" />
          </div>
          <div>
            <span className="font-montserrat font-bold text-navy text-sm">AI Budget Advisor</span>
            {generatedAt && <span className="ml-2 text-xs text-gray-400">Generated at {generatedAt}</span>}
          </div>
        </div>
        <div className="flex items-center gap-2">
          {advice && (
            <>
              <button onClick={copy} className="btn-outline btn-sm px-2" title="Copy"><Copy size={13} /></button>
              <button onClick={print} className="btn-outline btn-sm px-2" title="Print"><Printer size={13} /></button>
              <button onClick={generate} disabled={loading} className="btn-outline btn-sm px-2" title="Regenerate">
                <RefreshCw size={13} className={loading ? 'animate-spin' : ''} />
              </button>
            </>
          )}
          {!advice && (
            <button onClick={generate} disabled={loading}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded-lg text-xs font-semibold transition-all disabled:opacity-50">
              {loading
                ? <><div className="animate-spin rounded-full h-3 w-3 border-b-2 border-white" /> Analyzing...</>
                : <><Sparkles size={12} /> Get Budget Advice</>}
            </button>
          )}
        </div>
      </div>

      {error && <div className="p-4 text-sm text-red bg-red/5">{error}</div>}

      {loading && (
        <div className="p-8 text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto mb-3" />
          <p className="text-sm text-gray-400">Analyzing budget allocations and spending patterns...</p>
          <p className="text-xs text-gray-300 mt-1">This may take 5-10 seconds</p>
        </div>
      )}

      {advice && !loading && (
        <div className="p-5">
          <div className="prose prose-sm max-w-none">
            {advice.split('\n').filter(p => p.trim()).map((para, i) => (
              <p key={i} className="text-sm text-gray-700 leading-relaxed mb-3">{para}</p>
            ))}
          </div>
          <div className="text-xs text-gray-300 text-right mt-2">Powered by MUTCU AI Assistant · {spiritualYear}</div>
        </div>
      )}

      {!advice && !loading && !error && (
        <div className="p-6 text-center text-gray-400 text-sm">
          <Sparkles size={20} className="mx-auto mb-2 text-purple-200" />
          <p>Get an AI-powered analysis of your budget allocations vs actual spending.</p>
          <p className="text-xs mt-1 text-gray-300">Identifies over-budget ministries, low utilization, and provides actionable recommendations.</p>
        </div>
      )}
    </div>
  )
}