import { useState } from 'react'
import api from '../../lib/api'
import toast from 'react-hot-toast'
import { Sparkles, RefreshCw, Copy, Printer, TrendingUp, FileText, AlertTriangle, CheckCircle } from 'lucide-react'

// ─── AI Financial Narrative ───────────────────────────────────
function AIFinancialNarrative({ spiritualYear }) {
  const [loading, setLoading] = useState(false)
  const [narrative, setNarrative] = useState(null)
  const [error, setError] = useState(null)

  const generate = async () => {
    if (!spiritualYear) return toast.error('Select a financial year first')
    setLoading(true); setError(null)
    try {
      const res = await api.post('/ai/treasury/financial-narrative', { spiritual_year: spiritualYear })
      setNarrative(res.data.narrative)
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate narrative')
    } finally { setLoading(false) }
  }

  const copy = () => { navigator.clipboard.writeText(narrative || ''); toast.success('Copied!') }

  const print = () => {
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>MUTCU Financial Summary — ${spiritualYear}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#04003D;max-width:700px;margin:0 auto;}
      h1{color:#04003D;border-bottom:3px solid #FF9700;padding-bottom:10px;}
      p{line-height:1.9;color:#374151;margin-bottom:16px;}
      .footer{margin-top:40px;font-size:12px;color:#9CA3AF;border-top:1px solid #E5E7EB;padding-top:10px;}
      </style></head><body>
      <h1>MUTCU Financial Summary Report</h1>
      <p><strong>Spiritual Year:</strong> ${spiritualYear}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p>
      <hr style="border:none;border-top:1px solid #E5E7EB;margin:20px 0;">
      ${(narrative || '').split('\n').filter(p => p.trim()).map(p => `<p>${p}</p>`).join('')}
      <div class="footer">Generated by MUTCU AI Assistant · portal.mutcu.org · For official use only</div>
      </body></html>
    `)
    win.document.close(); win.print()
  }

  return (
    <div className="card border border-purple-100">
      <div className="flex items-center justify-between p-4 border-b border-gray-50">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-purple-100 rounded-lg flex items-center justify-center">
            <FileText size={14} className="text-purple-600" />
          </div>
          <div>
            <span className="font-montserrat font-bold text-navy text-sm">AI Financial Narrative</span>
            <p className="text-xs text-gray-400">For EC meetings & AGM presentations</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {narrative && (
            <>
              <button onClick={copy} className="btn-outline btn-sm px-2" title="Copy"><Copy size={13} /></button>
              <button onClick={print} className="btn-outline btn-sm px-2" title="Print"><Printer size={13} /></button>
              <button onClick={generate} disabled={loading} className="btn-outline btn-sm px-2">
                <RefreshCw size={13} className={loading ? 'animate-spin' : ''} />
              </button>
            </>
          )}
          {!narrative && (
            <button onClick={generate} disabled={loading}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded-lg text-xs font-semibold disabled:opacity-50">
              {loading ? <><div className="animate-spin rounded-full h-3 w-3 border-b-2 border-white" /> Writing...</> : <><Sparkles size={12} /> Generate Narrative</>}
            </button>
          )}
        </div>
      </div>

      {error && <div className="p-4 text-sm text-red bg-red/5">{error}</div>}
      {loading && (
        <div className="p-8 text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto mb-3" />
          <p className="text-sm text-gray-400">Writing your financial narrative...</p>
        </div>
      )}
      {narrative && !loading && (
        <div className="p-5">
          {narrative.split('\n').filter(p => p.trim()).map((para, i) => (
            <p key={i} className="text-sm text-gray-700 leading-relaxed mb-3">{para}</p>
          ))}
          <div className="text-xs text-gray-300 text-right mt-2">MUTCU AI Assistant · {spiritualYear}</div>
        </div>
      )}
      {!narrative && !loading && !error && (
        <div className="p-6 text-center text-gray-400 text-sm">
          <FileText size={20} className="mx-auto mb-2 text-purple-200" />
          <p>Generate a professional 4-5 paragraph financial narrative for your EC meeting or AGM.</p>
        </div>
      )}
    </div>
  )
}

// ─── AI Income Forecaster ─────────────────────────────────────
function AIIncomeForecaster({ spiritualYear }) {
  const [loading, setLoading] = useState(false)
  const [forecast, setForecast] = useState(null)
  const [message, setMessage] = useState(null)
  const [error, setError] = useState(null)

  const generate = async () => {
    if (!spiritualYear) return toast.error('Select a financial year first')
    setLoading(true); setError(null); setForecast(null); setMessage(null)
    try {
      const res = await api.post('/ai/treasury/income-forecast', { spiritual_year: spiritualYear })
      if (res.data.forecast) setForecast(res.data.forecast)
      else setMessage(res.data.message)
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate forecast')
    } finally { setLoading(false) }
  }

  const confidenceColor = { LOW: 'text-red', MEDIUM: 'text-orange', HIGH: 'text-teal' }

  return (
    <div className="card border border-purple-100">
      <div className="flex items-center justify-between p-4 border-b border-gray-50">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-purple-100 rounded-lg flex items-center justify-center">
            <TrendingUp size={14} className="text-purple-600" />
          </div>
          <div>
            <span className="font-montserrat font-bold text-navy text-sm">AI Income Forecast</span>
            <p className="text-xs text-gray-400">Projected income for the rest of the year</p>
          </div>
        </div>
        <button onClick={generate} disabled={loading}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded-lg text-xs font-semibold disabled:opacity-50">
          {loading ? <><div className="animate-spin rounded-full h-3 w-3 border-b-2 border-white" /> Forecasting...</> : <><Sparkles size={12} /> {forecast ? 'Refresh' : 'Forecast Income'}</>}
        </button>
      </div>

      {error && <div className="p-4 text-sm text-red bg-red/5">{error}</div>}
      {loading && (
        <div className="p-8 text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto mb-3" />
          <p className="text-sm text-gray-400">Analyzing income patterns and projecting forward...</p>
        </div>
      )}
      {message && !loading && (
        <div className="p-5 text-center text-gray-400 text-sm">
          <AlertTriangle size={20} className="mx-auto mb-2 text-orange" />
          {message}
        </div>
      )}
      {forecast && !loading && (
        <div className="p-5 space-y-4">
          {/* Forecast range */}
          <div className="grid grid-cols-3 gap-3">
            <div className="text-center bg-gray-50 rounded-xl p-3">
              <div className="text-xs text-gray-400 mb-1">Low Estimate</div>
              <div className="font-montserrat font-bold text-navy">KES {parseFloat(forecast.projected_low || 0).toLocaleString()}</div>
            </div>
            <div className="text-center bg-purple-50 rounded-xl p-3 border border-purple-200">
              <div className="text-xs text-purple-500 font-semibold mb-1">Midpoint</div>
              <div className="font-montserrat font-bold text-purple-700 text-lg">KES {parseFloat(forecast.projected_midpoint || 0).toLocaleString()}</div>
            </div>
            <div className="text-center bg-gray-50 rounded-xl p-3">
              <div className="text-xs text-gray-400 mb-1">High Estimate</div>
              <div className="font-montserrat font-bold text-navy">KES {parseFloat(forecast.projected_high || 0).toLocaleString()}</div>
            </div>
          </div>

          {/* Stats */}
          <div className="flex items-center gap-4 text-xs text-gray-500 flex-wrap">
            <span>Recorded so far: <strong className="text-teal">KES {parseFloat(forecast.recorded_so_far || 0).toLocaleString()}</strong></span>
            <span>Weeks remaining: <strong className="text-navy">{forecast.weeks_remaining}</strong></span>
            {forecast.confidence && (
              <span>Confidence: <strong className={confidenceColor[forecast.confidence] || 'text-gray-600'}>{forecast.confidence}</strong></span>
            )}
          </div>

          {/* Assumptions */}
          {forecast.assumptions && (
            <div className="bg-gray-50 rounded-xl p-3">
              <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-1">Key Assumptions</div>
              <p className="text-xs text-gray-600">{forecast.assumptions}</p>
            </div>
          )}

          {/* Recommendations */}
          {forecast.recommendations?.length > 0 && (
            <div>
              <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">Recommendations</div>
              <div className="space-y-1">
                {forecast.recommendations.map((r, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-gray-600">
                    <CheckCircle size={12} className="text-teal flex-shrink-0 mt-0.5" />
                    {r}
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="text-xs text-gray-300 text-right">MUTCU AI Assistant · {spiritualYear}</div>
        </div>
      )}
      {!forecast && !loading && !error && !message && (
        <div className="p-6 text-center text-gray-400 text-sm">
          <TrendingUp size={20} className="mx-auto mb-2 text-purple-200" />
          <p>Forecast projected income for the rest of the financial year based on historical patterns.</p>
        </div>
      )}
    </div>
  )
}

// ─── Main Export: Combined AI Financial Panel ─────────────────
export default function AIFinancialPanel({ spiritualYear }) {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-2">
        <Sparkles size={16} className="text-purple-600" />
        <h2 className="font-montserrat font-bold text-navy text-sm">AI Financial Intelligence</h2>
        <span className="text-xs text-gray-400">— Powered by MUTCU AI Assistant</span>
      </div>
      <AIFinancialNarrative spiritualYear={spiritualYear} />
      <AIIncomeForecaster spiritualYear={spiritualYear} />
    </div>
  )
}

export { AIFinancialNarrative, AIIncomeForecaster }