import { useState } from 'react'
import api from '../../lib/api'
import toast from 'react-hot-toast'
import { Sparkles, FileText, Megaphone, Shield, Copy, Check, RefreshCw } from 'lucide-react'

// ─── Reusable AI Tool Card ────────────────────────────────────
function AIToolCard({ icon: Icon, title, desc, color, children }) {
  return (
    <div className="card overflow-hidden">
      <div className="card-header">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${color}`}>
            <Icon size={16} className="text-white" />
          </div>
          <div>
            <h3 className="font-montserrat font-bold text-navy text-sm">{title}</h3>
            <p className="text-xs text-gray-400">{desc}</p>
          </div>
        </div>
        <div className="flex items-center gap-1 text-xs text-purple-500 bg-purple-50 px-2 py-1 rounded-full">
          <Sparkles size={11} /> AI Powered
        </div>
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

// ─── Copy Button ──────────────────────────────────────────────
function CopyButton({ text }) {
  const [copied, setCopied] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button onClick={copy} className="btn-outline btn-sm text-xs">
      {copied ? <><Check size={12} /> Copied!</> : <><Copy size={12} /> Copy</>}
    </button>
  )
}

// ─── Result Box ───────────────────────────────────────────────
function ResultBox({ result, label }) {
  if (!result) return null
  return (
    <div className="mt-4 bg-purple-50 border border-purple-200 rounded-xl p-4">
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-semibold text-purple-500 uppercase tracking-wide">{label || 'AI Result'}</span>
        <CopyButton text={result} />
      </div>
      <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">{result}</div>
    </div>
  )
}

// ─── Meeting Minutes ──────────────────────────────────────────
function MeetingMinutes() {
  const [rawNotes, setRawNotes] = useState('')
  const [meetingDate, setMeetingDate] = useState(new Date().toISOString().split('T')[0])
  const [attendees, setAttendees] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!rawNotes.trim()) return toast.error('Paste your raw meeting notes first')
    setLoading(true)
    try {
      const res = await api.post('/ai/admin/meeting-minutes', { raw_notes: rawNotes, meeting_date: meetingDate, attendees })
      setResult(res.data.minutes)
    } catch (err) { toast.error(err.response?.data?.error || 'Failed') }
    finally { setLoading(false) }
  }

  const printMinutes = () => {
    if (!result) return
    const win = window.open('', '_blank')
    win.document.write(`<html><head><title>MUTCU EC Meeting Minutes</title>
    <style>body{font-family:Arial,sans-serif;padding:40px;color:#04003D;max-width:700px;margin:0 auto;}
    h1{color:#04003D;border-bottom:3px solid #FF9700;padding-bottom:10px;}
    pre{white-space:pre-wrap;font-family:Arial,sans-serif;line-height:1.8;}
    .footer{margin-top:40px;font-size:11px;color:#9CA3AF;border-top:1px solid #E5E7EB;padding-top:10px;}
    </style></head><body>
    <h1>MUTCU EC Meeting Minutes</h1>
    <p><strong>Date:</strong> ${meetingDate}</p>
    <hr style="border:none;border-top:1px solid #E5E7EB;margin:16px 0;">
    <pre>${result}</pre>
    <div class="footer">Generated by MUTCU AI Assistant · portal.mutcu.org</div>
    </body></html>`)
    win.document.close(); win.print()
  }

  return (
    <AIToolCard icon={FileText} title="Meeting Minutes Summarizer" desc="Paste raw EC meeting notes → get clean formatted minutes" color="bg-purple-600">
      <div className="space-y-3">
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="form-label">Meeting Date</label>
            <input type="date" className="form-input" value={meetingDate} onChange={e => setMeetingDate(e.target.value)} />
          </div>
          <div>
            <label className="form-label">Attendees (optional)</label>
            <input className="form-input" placeholder="e.g. Purdri, Faith, Mercy..." value={attendees} onChange={e => setAttendees(e.target.value)} />
          </div>
        </div>
        <div>
          <label className="form-label">Raw Meeting Notes <span className="text-orange">*</span></label>
          <textarea className="form-input" rows={6} placeholder="Paste your raw meeting notes here — bullet points, shorthand, anything..."
            value={rawNotes} onChange={e => setRawNotes(e.target.value)} />
        </div>
        <div className="flex gap-2">
          <button onClick={generate} disabled={loading || !rawNotes.trim()} className="btn-primary">
            {loading ? <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" /> Formatting...</> : <><Sparkles size={14} /> Format Minutes</>}
          </button>
          {result && <button onClick={printMinutes} className="btn-outline btn-sm">🖨️ Print</button>}
          {result && <button onClick={() => setResult(null)} className="btn-outline btn-sm"><RefreshCw size={13} /></button>}
        </div>
        <ResultBox result={result} label="Formatted Meeting Minutes" />
      </div>
    </AIToolCard>
  )
}

// ─── Announcement Composer ────────────────────────────────────
function AnnouncementComposer() {
  const [topic, setTopic] = useState('')
  const [tone, setTone] = useState('Professional and warm')
  const [details, setDetails] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!topic.trim()) return toast.error('Enter a topic first')
    setLoading(true)
    try {
      const res = await api.post('/ai/admin/compose-announcement', { topic, tone, additional_details: details })
      setResult(res.data.announcement)
    } catch (err) { toast.error(err.response?.data?.error || 'Failed') }
    finally { setLoading(false) }
  }

  const useAnnouncement = async () => {
    if (!result) return
    try {
      await api.post('/announcements', { title: topic, body: result, is_published: false })
      toast.success('Saved as draft announcement! Go to Announcements to publish.')
    } catch { toast.error('Failed to save — copy and paste manually') }
  }

  return (
    <AIToolCard icon={Megaphone} title="Announcement Composer" desc="Describe what you want to announce → AI drafts it" color="bg-orange">
      <div className="space-y-3">
        <div>
          <label className="form-label">Topic / What to Announce <span className="text-orange">*</span></label>
          <input className="form-input" placeholder="e.g. Prayer Kesha this Friday at 6pm, all members welcome"
            value={topic} onChange={e => setTopic(e.target.value)} />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="form-label">Tone</label>
            <select className="form-select" value={tone} onChange={e => setTone(e.target.value)}>
              <option>Professional and warm</option>
              <option>Urgent and important</option>
              <option>Celebratory and exciting</option>
              <option>Formal and official</option>
              <option>Casual and friendly</option>
            </select>
          </div>
          <div>
            <label className="form-label">Additional Details</label>
            <input className="form-input" placeholder="Venue, time, who to contact..."
              value={details} onChange={e => setDetails(e.target.value)} />
          </div>
        </div>
        <div className="flex gap-2">
          <button onClick={generate} disabled={loading || !topic.trim()} className="btn-primary">
            {loading ? <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" /> Writing...</> : <><Sparkles size={14} /> Draft Announcement</>}
          </button>
          {result && <button onClick={() => generate()} className="btn-outline btn-sm"><RefreshCw size={13} /> Redo</button>}
        </div>
        <ResultBox result={result} label="Drafted Announcement" />
        {result && (
          <button onClick={useAnnouncement} className="btn-teal btn-sm mt-2">
            <Megaphone size={13} /> Save as Draft Announcement
          </button>
        )}
      </div>
    </AIToolCard>
  )
}

// ─── Disciplinary Advisor ─────────────────────────────────────
function DisciplinaryAdvisor() {
  const [offense, setOffense] = useState('')
  const [severity, setSeverity] = useState('moderate')
  const [history, setHistory] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!offense.trim()) return toast.error('Describe the offense first')
    setLoading(true)
    try {
      const res = await api.post('/ai/admin/disciplinary-advice', { offense_description: offense, severity, member_history: history })
      setResult(res.data.advice)
    } catch (err) { toast.error(err.response?.data?.error || 'Failed') }
    finally { setLoading(false) }
  }

  return (
    <AIToolCard icon={Shield} title="Disciplinary Case Advisor" desc="Describe the situation → AI advises on constitutional process" color="bg-red">
      <div className="bg-orange/5 border border-orange/20 rounded-xl p-3 mb-4 text-xs text-orange">
        ⚠️ This is AI guidance only. Always refer to the MUTCU Constitution 2025 and consult the Advisory Board for serious cases.
      </div>
      <div className="space-y-3">
        <div>
          <label className="form-label">Offense Description <span className="text-orange">*</span></label>
          <textarea className="form-input" rows={3} placeholder="Describe the nature of the offense or conduct concern..."
            value={offense} onChange={e => setOffense(e.target.value)} />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="form-label">Severity</label>
            <select className="form-select" value={severity} onChange={e => setSeverity(e.target.value)}>
              <option value="minor">Minor</option>
              <option value="moderate">Moderate</option>
              <option value="serious">Serious</option>
              <option value="critical">Critical</option>
            </select>
          </div>
          <div>
            <label className="form-label">Prior History (optional)</label>
            <input className="form-input" placeholder="e.g. First offense, or prior warning..."
              value={history} onChange={e => setHistory(e.target.value)} />
          </div>
        </div>
        <button onClick={generate} disabled={loading || !offense.trim()} className="btn-primary">
          {loading ? <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" /> Advising...</> : <><Sparkles size={14} /> Get Constitutional Guidance</>}
        </button>
        <ResultBox result={result} label="Constitutional Guidance" />
      </div>
    </AIToolCard>
  )
}

// ─── Nomination Announcement Drafter ─────────────────────────
function NominationAnnouncementDrafter() {
  const [form, setForm] = useState({
    cycle_title: '', spiritual_year: `${new Date().getFullYear()}/${new Date().getFullYear() + 1}`,
    nomination_open_date: '', nomination_close_date: '', agm_date: '', positions: ''
  })
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!form.cycle_title) return toast.error('Enter cycle title')
    setLoading(true)
    try {
      const res = await api.post('/ai/nominations/draft-announcement', form)
      setResult(res.data.announcement)
    } catch (err) { toast.error(err.response?.data?.error || 'Failed') }
    finally { setLoading(false) }
  }

  return (
    <AIToolCard icon={Megaphone} title="Nomination Announcement Drafter" desc="Generate WhatsApp + notice board announcements for nomination cycles" color="bg-teal">
      <div className="space-y-3">
        <div className="grid grid-cols-2 gap-3">
          <div className="col-span-2">
            <label className="form-label">Cycle Title <span className="text-orange">*</span></label>
            <input className="form-input" placeholder="e.g. MUTCU Leadership Nominations 2026/2027"
              value={form.cycle_title} onChange={e => setForm(f => ({ ...f, cycle_title: e.target.value }))} />
          </div>
          <div>
            <label className="form-label">Nominations Open</label>
            <input type="date" className="form-input" value={form.nomination_open_date}
              onChange={e => setForm(f => ({ ...f, nomination_open_date: e.target.value }))} />
          </div>
          <div>
            <label className="form-label">Nominations Close</label>
            <input type="date" className="form-input" value={form.nomination_close_date}
              onChange={e => setForm(f => ({ ...f, nomination_close_date: e.target.value }))} />
          </div>
        </div>
        <button onClick={generate} disabled={loading || !form.cycle_title} className="btn-primary">
          {loading ? <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" /> Drafting...</> : <><Sparkles size={14} /> Draft Announcements</>}
        </button>
        {result && (
          <div className="space-y-3 mt-4">
            <div className="bg-green-50 border border-green-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-green-600 uppercase">📱 WhatsApp Message</span>
                <CopyButton text={result.whatsapp || ''} />
              </div>
              <p className="text-sm text-gray-700 whitespace-pre-wrap">{result.whatsapp}</p>
            </div>
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-blue-600 uppercase">📋 Notice Board</span>
                <CopyButton text={result.notice_board || ''} />
              </div>
              <p className="text-sm text-gray-700 whitespace-pre-wrap">{result.notice_board}</p>
            </div>
          </div>
        )}
      </div>
    </AIToolCard>
  )
}

// ─── Main Page ────────────────────────────────────────────────
export default function AdminAI() {
  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">AI Assistant</h1>
          <p className="page-subtitle">AI-powered tools for EC administration — powered by Groq</p>
        </div>
        <div className="flex items-center gap-2 text-xs text-purple-500 bg-purple-50 px-3 py-1.5 rounded-full border border-purple-200">
          <Sparkles size={12} /> MUTCU AI Assistant
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <MeetingMinutes />
        <AnnouncementComposer />
        <NominationAnnouncementDrafter />
        <DisciplinaryAdvisor />
      </div>
    </div>
  )
}